# Generated by Django 5.2.3 on 2025-06-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipe'},
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='RECIPE',
        ),
    ]
