# Generated by Django 5.2.1 on 2025-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
